const mongoose=require('mongoose')
const {Schema,model}=mongoose

const dataSchema=new Schema({
    basics:{
        name:String,
        designation:String,
        resume:String,
        video_resume:String,
        image:String,
        tagline:String,
        description:String,
        intro_video:String,
        summary:String,
        yearsOfExperience:Number,
        age:Number,
        residence:String,
        city:String,
    },
    education:[
        {
            institution:String,
            studyType:String,
            startDate:String,
            endDate:String
        }
    ],
    skills:[
        {
            name:String,
            percentage:Number,
            category:String
        }
    ],
    otherSkills:[],
    projects:[
        {
            name:String,
            description:String,
            image:String,
            liveUrl:String,
            gitHubLink:String,
            duration:Number
        }
    ],
    contact:{
        tagline:String,
        email:String,
        phone:Number,
        address:String,
        mapUrl:String,
        title:String,
        fbLink:String,
        linkedinLink:String,
        gitHubLink:String,
        instraLink:String,
        twitterLink:String,
        youtubeLink:String
    },
    contactList:[{
        type:Schema.Types.ObjectId,
        ref:"ContactList"
    }],
    testimonials:[],
    certifications:[],
})

const Data=model('Data',dataSchema)
module.exports=Data